name: Build and Sign Executable

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write
  id-token: write

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - uses: swatinem/rust-cache@v2

      - name: install dependencies (windows only)
        shell: pwsh
        run: |
          $releaseUrl = "https://github.com/Levminer/trusted-signing-cli/releases/latest/download/trusted-signing-cli-x86_64-pc-windows-msvc.zip"
          Invoke-WebRequest -Uri $releaseUrl -OutFile "trusted-signing-cli.zip"
          Expand-Archive -Path "trusted-signing-cli.zip" -DestinationPath "trusted-signing-cli"
          echo "$((Get-Item -Path ".\\trusted-signing-cli").FullName)" >> $env:GITHUB_PATH

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        id: tauri
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
